import express from "express";
import { Builder, By, until } from "selenium-webdriver";
const app = express();
// const Title_list = require('./singers.js');
import dotenv from "dotenv";
dotenv.config();

const Title_list = [
  "Yohani De Silva",
  "Sivaangi Krishnakumar",
  "Jyotica Tangri",
  "Aparna Balamurali",
  "Iman Chakraborty",
  "Sunanda Sharma",
  "Asees Kaur",
  "Dhvani Bhanushali",
  "Maitrayee Patar",
  "Rakshita Suresh",
  "Mannat Noor",
  "Jonita Gandhi",
  "Nikhita Gandhi",
  "Shirley Setia",
  "Vaikom Vijayalakshmi",
  "Kanika Kapoor",
  "Shalmali Kholgade",
  "Sravana Bhargavi",
  "Uthara Unnikrishnan",
  "Vandana Srinivasan",
  "Alka Ajith",
  "Antara Mitra",
  "Indu Nagaraj",
  "Jasmine Sandlas",
  "Mamta Sharma",
  "Shashaa Tirupati",
  "Nilanjana Sarkar",
  "Somlata Acharyya Chowdhury",
  "Abhirami Suresh",
  "June Banerjee",
  "Ranina Reddy",
  "Roopa Revathi",
  "Shakthisree Gopalan",
  "Amrutha Suresh",
  "Andrea Jeremiah",
  "Anitha Shaiq",
  "Megha",
  "Mridula Warrier",
  "Najim Arshad",
  "Prashanthini",
  "Priya Himesh",
  "Shazneen Arethna",
  "Sithara",
  "Akriti Kakar",
  "Anuradha Bhat",
  "Anushka Manchanda",
  "Anweshaa",
  "Geetha Madhuri",
  "Monali Thakur",
  "Neha Kakkar",
  "Sanchita Bhattacharya",
  "Tulsi Kumar",
  "Chaitra Ambadipudi",
  "Himani Kapoor",
  "Ranjini Jose",
  "Suvi Suresh",
  "Bhaswati Chakraborty",
  "Sona Mohapatra",
  "Kavita Seth",
  "Manjari",
  "Nihira Joshi",
  "Shruti Pathak",
  "Tanvi Shah",
  "Kalpana Raghavendar",
  "Mahathi",
  "Malvina",
  "Neeti Mohan",
  "Priyadarshini",
  "Reena Bhardwaj",
  "Shilpa Rao",
  "Shibani Kashyap",
  "Chaitra H. G.",
  "Charulatha Mani",
  "Chinmayi Sripada",
  "Jayati Chakraborty",
  "Sonu Kakkar",
  "Srilekha Parthasarathy",
  "Sunitha Sarathy",
  "Harshdeep Kaur",
  "Madhushree",
  "Malavika",
  "Saindhavi",
  "Anindita Paul",
  "Dominique Cerejo",
  "Richa Sharma",
  "Rimi Tomy",
  "Vaishali Samant",
  "Smita",
  "Bela Shende",
  "Shweta Pandit",
  "Usha",
  "A. R. Reihana",
  "Gayatri Asokan",
  "Jyotsna Radhakrishnan",
  "Nanditha",
  "Sanjeevani (Sanjeevani Bhelande)",
  "Shreya Ghoshal",
  "Mahalakshmi Iyer",
  "Nithyasree Mahadevan",
  "Palak Muchhal",
  "Rekha Bhardwaj",
  "Surmukhi Raman",
  "Gayatri Iyer (Gayatri Ganjawala)",
  "Shubha Mudgal",
  "Sunidhi Chauhan",
  "Queen Hazarika",
  "Bhavatharini",
  "Hard Kaur",
  "Harini",
  "Neha Rajpal (Nehha Rajpal) née 'Chandna' .",
  "Pop Shalini (Shalini Singh)",
  "Shweta Mohan",
  "Sunitha Upadrashta",
  "Tarali Sarma",
  "Anjali Marathe",
  "Jaspinder Narula",
  "Suzanne D'Mello",
  "Vasundhara Das",
  "Anuradha Sriram",
  "Ila Arun",
  "Kalpana Patowary",
  "Sowmya Raoh",
  "Annupamaa",
  "Bhitali Das",
  "Samantha Edwards",
  "Shweta Shetty",
  "Hema Sardesai",
  "Alisha Chinai",
  "Falguni Pathak",
  "Malgudi Subha",
  "Minmini",
  "Swarnalatha",
  "Sapna Mukherjee",
  "Anupama Deshpande",
  "Bombay Jayashri",
  "Sadhana Sargam",
  "Alka Yagnik",
  "Arundhati Holme Chowdhury",
  "Salma Agha",
  "Sharda Sinha",
  "K. S. Chithra (referred to as Chitra)",
  "Sagarika Mukherjee",
  "Chhaya Ganguly",
  "B. R. Chaya",
  "Sujatha",
  "S. P. Sailaja",
  "Arati Ankalikar-Tikekar",
  "Anuradha Paudwal",
  "Kavita Krishnamurthy",
  "Sushma Shrestha",
  "Vani Jayaram",
  "Kumari Kanchan Dinkerao Mail",
  "Hemlata",
  "Sulakshana Pandit",
  "Jency Anthony",
  "Usha Uthup",
  "Chitra Singh",
  "P. Madhuri",
  "Sharda Rajan Iyengar",
  "Jikki",
  "Banashree Sengupta",
  "Bangalore Latha",
  "Usha Khanna",
  "Ramakrishna V.",
  "S. Janaki",
  "Aarti Mukherji",
  "Mubarak Begum",
  "L. R. Eswari",
  "Usha Mangeshkar",
  "Sudha Malhotra",
  "Suman Kalyanpur",
  "Jagjit Kaur",
  "P. Susheela",
  "Santha P. Nair",
  "Bhagwanti Navani",
  "Rajkumari Dubey",
  "Sandhya Mukhopadhyay",
  "P. Leela",
  "K. Jamuna Rani",
  "Geeta Dutt",
  "Ruma Guha Thakurta",
  "Asha Bhosle",
  "Lata Mangeshkar",
  "Shamshad Begum",
  "P. Bhanumathi",
  "Rao Balasaraswathi Devi",
  "Amirbai Karnataki",
  "K. B. Sundarambal",
  "Kanan Devi",
  "Nimrat Khaira",
  "Name",
  "Premjeet Singh Dhillon",
  "32Stitches",
  "Sidhu Moose Wala",
  "Anurag Kulkarni",
  "Ami Mishra",
  "Gurshabad",
  "Pawandeep Rajan",
  "Vishal Mishra",
  "Amaal Mallik",
  "Darshan Raval",
  "Diwakar",
  "Happy Raikoti",
  "Hriday Gattani",
  "Jubin Nautiyal",
  "Sweekar Agasthi",
  "Anirudh Ravichander",
  "Guru Randhawa",
  "Jeet Gannguli",
  "Sundar Narayana Rao",
  "Aaman Trikha",
  "Ayushmann Khurrana",
  "Chandan Shetty",
  "Sid Sriram",
  "Tony Kakkar",
  "Thomson Andrews",
  "Arijit Singh",
  "Amit Mishra (singer)",
  "Dhanush",
  "Ankit Tiwari",
  "Mohammed Irfan",
  "Nakash Aziz",
  "Sachin Warrier",
  "Ash King",
  "Anuj Gurwara",
  "Krishna Iyer",
  "Mohan Rathore",
  "Parichay (singer)",
  "Rahul Sipligunj",
  "Yasser Desai",
  "Yo Yo Honey Singh",
  "Gajendra Verma",
  "Khesari Lal Yadav",
  "L. V. Revanth",
  "S. Thaman",
  "Tanishk Bagchi",
  "Tochi Raina",
  "Anupam Roy",
  "Armaan Malik",
  "Damodar Raao",
  "Najim Arshad",
  "Rupam Islam",
  "Suraj Jagan",
  "Badshah",
  "Noel Sean",
  "Abhijeet Sawant",
  "Haricharan",
  "Himesh Reshammiya",
  "Meet Bros",
  "Sreerama Chandra Mynampati",
  "Naresh Iyer",
  "NTR Jr.",
  "Rahul Vaidya",
  "Vishal Dadlani",
  "Diljit Dosanjh",
  "Krishna Beura",
  "Papon",
  "Vedala Hemachandra",
  "Vijay Prakash",
  "Alphons Joseph",
  "Jassie Gift",
  "Kailash Kher",
  "Blaaze",
  "Joi Barua",
  "Kunal Ganjawala",
  "Mohit Chauhan",
  "Silambarasan",
  "Soham Chakraborty",
  "Vineeth Sreenivasan",
  "Benny Dayal",
  "Amit Trivedi",
  "Bohemia",
  "Chetan Sosca",
  "Manikka Vinayagam",
  "Nitin Dubey",
  "Sriram Parthasarathy",
  "Pritam",
  "Javed Ali",
  "Saandip",
  "Sandeep Khurana",
  "Vijay Yesudas",
  "Clinton Cerejo",
  "Devan Ekambaram",
  "Devi Sri Prasad",
  "Karthik",
  "Madhu Balakrishnan",
  "Vishal Dadlani",
  "Babbu Maan",
  "Mika Singh",
  "S. P. B. Charan",
  "Shankar Mahadevan",
  "Sukhjinder virk",
  "Pawan Singh",
  "Shabab Sabri",
  "KK",
  "Aditya Narayan",
  "Daler Mehndi",
  "Navin Prabhakar",
  "Unnikrishnan",
  "Babul Supriyo",
  "Neeraj Shridhar",
  "Joseph Vijay",
  "Biju Narayanan",
  "Parthiv Gohil",
  "Pradip Somasundaran",
  "Sonu Nigam",
  "A. R. Rahman",
  "Roop Kumar Rathod",
  "Zubeen Garg",
  "Rajesh Krishnan",
  "Sukhwinder Singh",
  "M. M. Keeravani",
  "Master Saleem",
  "Shaan",
  "Kumar Sanu",
  "Sudesh Bhosle",
  "Mano",
  "G. Venugopal",
  "Vinod Rathod",
  "Mohammed Aziz",
  "M. G. Sreekumar",
  "Gurdas Maan",
  "Kamal Haasan",
  "Abhijeet Bhattacharya",
  "Unni Menon",
  "Puneeth Rajkumar",
  "Pankaj Udhas",
  "Shabbir Kumar",
  "Udit Narayan",
  "Anwar",
  "Suresh Wadkar",
  "Hariharan",
  "Lucky Ali",
  "Remo Fernandes",
  "Shailender Singh",
  "Nadeem Saifi",
  "Bappi Lahiri",
  "Nitin Mukesh",
  "S. P. Balasubrahmanyam",
  "Amit Kumar",
  "Jagjit Singh",
  "Dr. Rajkumar",
  "R. D. Burman",
  "P. Jayachandran",
  "Bhupinder Singh",
  "Jayanta Hazarika",
  "K. J. Yesudas",
  "Malaysia Vasudevan",
  "Mahendra Kapoor",
  "Manabendra Mukhopadhyay",
  "Kozhikode Abdul Kader",
  "P. B. Sreenivas",
  "Shyamal Mitra",
  "T. M. Soundararajan",
  "Kishore Kumar",
  "Talat Mahmood",
  "Dwijen Mukhopadhyay",
  "Mohammed Rafi",
  "Manna Dey",
  "Bhupen Hazarika",
  "Ghantasala",
  "Bhimsen Joshi",
  "Mukesh",
  "Dhananjay Bhattacharya",
  "Hemanta Mukherjee",
  "G. M. Durrani",
  "S. D. Burman",
  "K. L. Saigal",
  "Pankaj Mullick",
  "Gursimran Singh Sidhu",
  "Anuv Jain",
  "Aashir Wajahat",
  "Akhil Sachdeva",
  "Jasleen Royal",
  "Manan Bhardwaj",
  "Akashdeep Sengupta",
  "Various Artists",
  "AUR",
  "Mithoon",
  "Justh",
  "OAFF",
  "Sachet Tandon",
  "Harshavardhan Rameshwar",
  "King",
  "Mismatched - Cast",
  "Raghav Chaitanya",
  "Rajat Nagpal",
  "Vishal-Shekhar",
  "Sachin-Jigar",
  "Denny",
  "Javed-Mohsin",
  "B Praak",
  "Payal Dev",
  "Kaifi Khalil",
  "A.R. Rahman",
  "Salim–Sulaiman",
  "Shankar-Ehsaan-Loy",
  "Jatin-Lalit",
  "Monty Sharma",
  "Madan Mohan",
  "Anu Malik",
  "Sajid-Wajid",
  "Ram Sampath",
  "Adnan Sami",
  "Nadeem Shravan",
  "Anand Raj Anand",
  "Vishal Bhardwaj",
  "Sandesh Shandilya",
  "Sandeep Chowta",
  "Sachet-Parampara",
  "Atif Aslam",
  "Rochak Kohli",
  "Shaarib Toshi",
  "Ajay-Atul",
  "Bobby-Imran",
  "Anand-Milind",
  "Viju Shah",
  "Uttam Singh",
  "Bhushan Dua",
  "Vishal",
  "Ismail Darbar",
  "Dilip Sen- Sameer Sen",
  "Rajesh Roshan",
  "Ram Laxman",
  "Laxmikant–Pyarelal",
  "Raamlaxman",
  "Raam Laxman",
  "Raghav",
  "Lijo George-Dj Chetas",
  "Yash Narvekar",
  "Sanjay Leela Bhansali",
  "Jaani",
  "Sohail Sen",
  "Yohani",
  "Akhil",
  "Shantanu Moitra",
  "Nikhil Vinay",
  "Lata Mangeshkar,Udit Narayan",
  "Savi Kahlon",
  "Hasan Raheem",
  "Shubh",
  "Sharn",
  "Ali Zafar",
  "AP Dhillon",
  "Harrdy Sandhu",
  "Abhijeet Srivastava",
  "Shiv Hari",
  "Sajid-Wajid Khan",
  "Yashraj Mukhate",
  "Raftaar",
  "W.i.S.H.",
  "Shraddha Pandit",
  "Sanjith Hegde",
  "Anand Bhaskar",
  "Laqshay Kapoor",
  "Madhur Sharma",
  "Shekhar Ravjiani",
  "Mitraz",
  "JalRaj",
  "Suzonn",
  "Aadya",
  "Talwiinder",
  "Diesby",
  "Imran Khan Sitar",
  "Adnan Ahmad",
  "Pratsofficial",
  "Asim Azhar",
  "Zaeden",
  "Dhruv Visvanath",
  "KASYAP",
  "Vikram Montrose",
  "Kalyanji-Anandji",
  "Priyanshi Srivastava",
  "Shashwat Sachdev",
  "Nitinn Kumar",
  "Avishek",
  "Varun Grover",
  "Anmol Daniel",
  "Rashmi Virag",
  "Nikhil D'Souza",
  "Hansika Pareek",
  "Faisal Kapadia",
  "Shashwat Singh",
  "Kushagra",
  "Dikshant",
  "Rahul Mishra",
  "Simar Sethi",
  "Lisa Mishra",
  "Nakul Chugh",
  "Akanksha Sethi",
  "Yung Delic",
  "Bharatt-Saurabh",
  "Anmol Malik",
  "Vilen",
  "Tanzeel Khan",
  "Dino James",
  "Ranita Banerjee",
  "Saaj Bhatt",
  "Khwaab",
  "Iqlipse Nova",
  "Aditya Rikhari",
  "Jigar Saraiya",
  "Stebin Ben",
  "Raghav Kaushik",
  "Nucleya",
  "MEDUZA",
  "MC SQUARE",
  "Dev Negi",
  "Sahir",
  "Dhruv Malik",
  "Ananya Birla",
  "Faridkot",
  "Chaar Diwaari",
  "Tarjani Hirani",
  "BAWA",
  "Meet Bros.",
  "Sakshi Holkar",
  "Nesz",
  "Faraz",
  "Swaalina",
  "Amit Mishra",
  "Mellow D",
  "Siddharth Slathia",
  "Hypia",
  "Aishwarya Majmudar",
  "Musaafir",
  "Aniirban Saha",
  "Bryxn",
  "Altamash Faridi",
  "Aniket Shukla",
  "Avishek Majumder",
  "Rinosh George",
  "Rashid Khan",
  "Shivam Srivastava",
  "Aditya Vashisht",
  "Prateek sheth dawesar",
  "Rahat Fateh Ali Khan",
  "DEW",
  "Raaj J Konwar",
  "Rishabh Shah",
  "Justin-Uday Duo",
  "Arjama B",
  "Shirish",
  "Taha G",
  "Mohit Aanand",
  "Shahid Mallya",
  "Sparsh Jain",
  "Karan Nawani",
  "Aaryan Banthia",
  "Ajayank",
  "Raj Barman",
  "Sanjana Devarajan",
  "Kaustubh Patil",
  "Sabali The Band",
  "Tarish Prakash",
  "Anusufi",
  "Shishir Singh",
  "Chinmay Agrawal",
  "KR$NA",
  "Farhan Khan",
  "Raga",
  "Fotty Seven",
  "JASKARAN",
  "Gravity",
  "Sikander Kahlon",
  "Simba Sing",
  "Nanku",
  "Emiway Bantai",
  "Frappe Ash",
  "Ikka",
  "Deep Kalsi",
  "Loka",
  "Sultaan",
  "Vijay Dk",
  "Karma",
  "KSHMR",
  "Karan Kanchan",
  "Nazz",
  "Pho",
  "DG IMMORTALS",
  "Yashraj",
  "SAMBATA",
  "Dakait",
  "MC STAN",
  "Munawar Faruqui",
  "Panther",
  "Shah Rule",
  "Kunwarr",
  "Bella",
  "Harjas Harjaayi",
  "yungsta",
  "Agsy",
  "Seedhe Maut",
  "Kaam Bhaari",
  "Young Galib",
  "Thoratt",
  "Paradox",
  "VIBIE",
  "KING",
  "Ravi Singhal",
  "Lo-fi 2307",
  "Kritiman Mishra",
  "Silent Ocean",
  "Jay Kava",
  "KSW",
  "Mann Taneja",
  "Class",
  "Lijo George",
  "Kaushik-Guddu",
  "M. M. Kreem",
  "RDB",
  "Harshit Saxena",
  "Chirantan Bhatt",
  "Jawad Ahmad",
  "Anurag Saikia",
  "Kuldeep Singh",
  "Uttam-Jagdish",
  "Ghulam Ali",
  "Ravindra Jain",
  "Ravi",
  "Khayyam",
  "Tabassum",
  "Salil Chowdhury",
  "Jaidev",
  "Rajkamal",
  "Naushad",
  "Shankar Jaikishan",
  "Arash",
  "Zack Knight",
  "Aastha Gill",
  "Mannan Shaah",
  "Maninder Buttar",
  "Millind Gaba",
  "Aditya Gadhvi",
  "Kanishk Seth",
  "Ved Sharma",
  "Kamal Barot",
  "Late Madan Mohan",
  "Yuvan Shankar Raja",
  "Hanif Shaikh",
  "Aryans",
  "Abhijeet",
  "Rohan Rohan",
  "Shivam Pathak",
  "R. Anandh",
  "Mathias Duplessy",
  "Vidyasagar",
  "MEMBA",
  "Priyanka Chopra",
  "Shirish Kunder",
  "Sachin Gupta",
  "Krsna Solo",
  "Hemant Kumar",
  "O. P. Nayyar",
  "Tabun Sutradhar",
  "Shamir Tandon",
  "C. Ramchandra",
  "Roshan",
  "Tanishk-Vayu",
  "Farida Khanum",
  "Suman Sridhar",
  "Mikey McCleary",
  "Mark K Robin",
  "Parth Bharat Thakkar",
  "Prateek Kuhad",
  "Osho Jain",
  "Arjun Kanungo",
];

app.get("/", async (req, res) => {
  console.log("Hello");
  let driver = await new Builder().forBrowser("chrome").build();
  try {
    await driver.get("https://accounts.spotify.com/en/login");
    // await driver.findElement(By.id('login-username')).sendKeys(id);
    // await driver.findElement(By.id('login-password')).sendKeys(pass);
    // await driver.findElement(By.id('login-button')).click();
    await driver.wait(async function () {
      const url = await driver.getCurrentUrl();
      return url.includes("https://accounts.spotify.com/en/status");
    }, 20000);
    let nextButton = await driver.wait(
      until.elementLocated(
        By.xpath('//*[@id="root"]/div/div[2]/div/div/button[2]')
      ),
      5000
    );
    await nextButton.click();

    // await driver.sleep(2000);
    let add_playlist = await driver.wait(
      until.elementLocated(
        By.xpath(
          '//*[@id="main"]/div/div[2]/div[1]/nav/div[2]/div[1]/div[1]/header/div/span/button'
        )
      ),
      5000
    );
    await add_playlist.click();
    await driver.sleep(2000);
    await driver
      .findElement(By.xpath('//*[@id="context-menu"]/ul/li[1]/button'))
      .click();
    await driver.sleep(2000);

    let likedSongs = await driver.wait(
      until.elementLocated(
        By.xpath(
          '//*[@id="main"]/div/div[2]/div[1]/nav/div[2]/div[1]/div[2]/div[4]/div/div/div/div[2]/ul/div/div[2]/li/div/div[1]'
        )
      ),
      5000
    );
    await likedSongs.click();

    const songs = await driver
      .wait(
        until.elementLocated(
          By.xpath(
            '//*[@id="main"]/div/div[2]/div[3]/div[1]/div[2]/div[2]/div/div/div[2]/main/section/div[1]/div[5]/div/span'
          )
        ),
        5000
      )
      .getText();
    const n = songs.split(" ")[0];

    for (let i = 0; i < n; i++) {
      const song_div = await driver
        .wait(
          until.elementLocated(
            By.xpath(
              `//*[@id="main"]/div/div[2]/div[3]/div[1]/div[2]/div[2]/div/div/div[2]/main/section/div[4]/div/div[2]/div[2]/div[${
                i + 1
              }]/div/div[2]/div/span/div`
            )
          ),
          5000
        )
        .getText();
      console.log(song_div);
      let singers = song_div.split(",");

      console.log(singers);
      if (i > 2) {
        const song_div_element = await driver.wait(
          until.elementLocated(
            By.xpath(
              `//*[@id="main"]/div/div[2]/div[3]/div[1]/div[2]/div[2]/div/div/div[2]/main/section/div[4]/div/div[2]/div[2]/div[${
                i - 1
              }]`
            )
          ),
          5000
        );
        driver.executeScript(
          "arguments[0].scrollIntoView();",
          song_div_element
        );
      }
      if (singers.some((item) => Title_list.includes(item))) {
        let option_button = await driver.wait(
          until.elementLocated(
            By.xpath(
              `//*[@id="main"]/div/div[2]/div[3]/div[1]/div[2]/div[2]/div/div/div[2]/main/section/div[4]/div/div[2]/div[2]/div[${
                i + 1
              }]/div/div[5]/button[2]`
            )
          ),
          5000
        );
        await option_button.click();
        await driver.sleep(2000);
        let playlist = await driver.wait(
          until.elementLocated(
            By.xpath('//*[@id="context-menu"]/ul/li[1]/button')
          ),
          5000
        );
        await playlist.click();
        await driver.sleep(2000);
        let button = await driver.executeScript(
          'return document.querySelector("#context-menu").querySelectorAll("button[tabindex=\'-1\']")[3];'
        );
        await driver.wait(until.elementIsVisible(button), 2000);
        await button.click();
        await driver.sleep(2000);
      }
    }
  } catch (error) {
    console.error(error);
    res.status(500).send({ error: error.toString() });
  } finally {
    // await driver.quit();
  }
});

app.listen(2000, () => console.log("Server running on port 2000"));
