const axios = require('axios');
const qs = require('qs');


let ID_list = [];

const Title_list = [
    "Yohani De Silva",
    "Sivaangi Krishnakumar",
    "Jyotica Tangri",
    "Aparna Balamurali",
    "Iman Chakraborty",
    "Sunanda Sharma",
    "Asees Kaur",
    "Dhvani Bhanushali",
    "Maitrayee Patar",
    "Rakshita Suresh",
    "Mannat Noor",
    "Jonita Gandhi",
    "Nikhita Gandhi",
    "Shirley Setia",
    "Vaikom Vijayalakshmi",
    "Kanika Kapoor",
    "Shalmali Kholgade",
    "Sravana Bhargavi",
    "Uthara Unnikrishnan",
    "Vandana Srinivasan",
    "Alka Ajith",
    "Antara Mitra",
    "Indu Nagaraj",
    "Jasmine Sandlas",
    "Mamta Sharma",
    "Shashaa Tirupati",
    "Nilanjana Sarkar",
    "Somlata Acharyya Chowdhury",
    "Abhirami Suresh",
    "June Banerjee",
    "Ranina Reddy",
    "Roopa Revathi",
    "Shakthisree Gopalan",
    "Amrutha Suresh",
    "Andrea Jeremiah",
    "Anitha Shaiq",
    "Megha",
    "Mridula Warrier",
    "Najim Arshad",
    "Prashanthini",
    "Priya Himesh",
    "Shazneen Arethna",
    "Sithara",
    "Akriti Kakar",
    "Anuradha Bhat",
    "Anushka Manchanda",
    "Anweshaa",
    "Geetha Madhuri",
    "Monali Thakur",
    "Neha Kakkar",
    "Sanchita Bhattacharya",
    "Tulsi Kumar",
    "Chaitra Ambadipudi",
    "Himani Kapoor",
    "Ranjini Jose",
    "Suvi Suresh",
    "Bhaswati Chakraborty",
    "Sona Mohapatra",
    "Kavita Seth",
    "Manjari",
    "Nihira Joshi",
    "Shruti Pathak",
    "Tanvi Shah",
    "Kalpana Raghavendar",
    "Mahathi",
    "Malvina",
    "Neeti Mohan",
    "Priyadarshini",
    "Reena Bhardwaj",
    "Shilpa Rao",
    "Shibani Kashyap",
    "Chaitra H. G.",
    "Charulatha Mani",
    "Chinmayi Sripada",
    "Jayati Chakraborty",
    "Sonu Kakkar",
    "Srilekha Parthasarathy",
    "Sunitha Sarathy",
    "Harshdeep Kaur",
    "Madhushree",
    "Malavika",
    "Saindhavi",
    "Anindita Paul",
    "Dominique Cerejo",
    "Richa Sharma",
    "Rimi Tomy",
    "Vaishali Samant",
    "Smita",
    "Bela Shende",
    "Shweta Pandit",
    "Usha",
    "A. R. Reihana",
    "Gayatri Asokan",
    "Jyotsna Radhakrishnan",
    "Nanditha",
    "Sanjeevani (Sanjeevani Bhelande)",
    "Shreya Ghoshal",
    "Mahalakshmi Iyer",
    "Nithyasree Mahadevan",
    "Palak Muchhal",
    "Rekha Bhardwaj",
    "Surmukhi Raman",
    "Gayatri Iyer (Gayatri Ganjawala)",
    "Shubha Mudgal",
    "Sunidhi Chauhan",
    "Queen Hazarika",
    "Bhavatharini",
    "Hard Kaur",
    "Harini",
    "Neha Rajpal (Nehha Rajpal) née 'Chandna' .",
    "Pop Shalini (Shalini Singh)",
    "Shweta Mohan",
    "Sunitha Upadrashta",
    "Tarali Sarma",
    "Anjali Marathe",
    "Jaspinder Narula",
    "Suzanne D'Mello",
    "Vasundhara Das",
    "Anuradha Sriram",
    "Ila Arun",
    "Kalpana Patowary",
    "Sowmya Raoh",
    "Annupamaa",
    "Bhitali Das",
    "Samantha Edwards",
    "Shweta Shetty",
    "Hema Sardesai",
    "Alisha Chinai",
    "Falguni Pathak",
    "Malgudi Subha",
    "Minmini",
    "Swarnalatha",
    "Sapna Mukherjee",
    "Anupama Deshpande",
    "Bombay Jayashri",
    "Sadhana Sargam",
    "Alka Yagnik",
    "Arundhati Holme Chowdhury",
    "Salma Agha",
    "Sharda Sinha",
    "K. S. Chithra (referred to as Chitra)",
    "Sagarika Mukherjee",
    "Chhaya Ganguly",
    "B. R. Chaya",
    "Sujatha",
    "S. P. Sailaja",
    "Arati Ankalikar-Tikekar",
    "Anuradha Paudwal",
    "Kavita Krishnamurthy",
    "Sushma Shrestha",
    "Vani Jayaram",
    "Kumari Kanchan Dinkerao Mail",
    "Hemlata",
    "Sulakshana Pandit",
    "Jency Anthony",
    "Usha Uthup",
    "Chitra Singh",
    "P. Madhuri",
    "Sharda Rajan Iyengar",
    "Jikki",
    "Banashree Sengupta",
    "Bangalore Latha",
    "Usha Khanna",
    "Ramakrishna V.",
    "S. Janaki",
    "Aarti Mukherji",
    "Mubarak Begum",
    "L. R. Eswari",
    "Usha Mangeshkar",
    "Sudha Malhotra",
    "Suman Kalyanpur",
    "Jagjit Kaur",
    "P. Susheela",
    "Santha P. Nair",
    "Bhagwanti Navani",
    "Rajkumari Dubey",
    "Sandhya Mukhopadhyay",
    "P. Leela",
    "K. Jamuna Rani",
    "Geeta Dutt",
    "Ruma Guha Thakurta",
    "Asha Bhosle",
    "Lata Mangeshkar",
    "Shamshad Begum",
    "P. Bhanumathi",
    "Rao Balasaraswathi Devi",
    "Amirbai Karnataki",
    "K. B. Sundarambal",
    "Kanan Devi",
    "Nimrat Khaira",
    "Name",
    "Premjeet Singh Dhillon",
    "32Stitches",
    "Sidhu Moose Wala",
    "Anurag Kulkarni",
    "Ami Mishra",
    "Gurshabad",
    "Pawandeep Rajan",
    "Vishal Mishra",
    "Amaal Mallik",
    "Darshan Raval",
    "Diwakar",
    "Happy Raikoti",
    "Hriday Gattani",
    "Jubin Nautiyal",
    "Sweekar Agasthi",
    "Anirudh Ravichander",
    "Guru Randhawa",
    "Jeet Gannguli",
    "Sundar Narayana Rao",
    "Aaman Trikha",
    "Ayushmann Khurrana",
    "Chandan Shetty",
    "Sid Sriram",
    "Tony Kakkar",
    "Thomson Andrews",
    "Arijit Singh",
    "Amit Mishra (singer)",
    "Dhanush",
    "Ankit Tiwari",
    "Mohammed Irfan",
    "Nakash Aziz",
    "Sachin Warrier",
    "Ash King",
    "Anuj Gurwara",
    "Krishna Iyer",
    "Mohan Rathore",
    "Parichay (singer)",
    "Rahul Sipligunj",
    "Yasser Desai",
    "Yo Yo Honey Singh",
    "Gajendra Verma",
    "Khesari Lal Yadav",
    "L. V. Revanth",
    "S. Thaman",
    "Tanishk Bagchi",
    "Tochi Raina",
    "Anupam Roy",
    "Armaan Malik",
    "Damodar Raao",
    "Najim Arshad",
    "Rupam Islam",
    "Suraj Jagan",
    "Badshah",
    "Noel Sean",
    "Abhijeet Sawant",
    "Haricharan",
    "Himesh Reshammiya",
    "Meet Bros",
    "Sreerama Chandra Mynampati",
    "Naresh Iyer",
    "NTR Jr.",
    "Rahul Vaidya",
    "Vishal Dadlani",
    "Diljit Dosanjh",
    "Krishna Beura",
    "Papon",
    "Vedala Hemachandra",
    "Vijay Prakash",
    "Alphons Joseph",
    "Jassie Gift",
    "Kailash Kher",
    "Blaaze",
    "Joi Barua",
    "Kunal Ganjawala",
    "Mohit Chauhan",
    "Silambarasan",
    "Soham Chakraborty",
    "Vineeth Sreenivasan",
    "Benny Dayal",
    "Amit Trivedi",
    "Bohemia",
    "Chetan Sosca",
    "Manikka Vinayagam",
    "Nitin Dubey",
    "Sriram Parthasarathy",
    "Pritam",
    "Javed Ali",
    "Saandip",
    "Sandeep Khurana",
    "Vijay Yesudas",
    "Clinton Cerejo",
    "Devan Ekambaram",
    "Devi Sri Prasad",
    "Karthik",
    "Madhu Balakrishnan",
    "Vishal Dadlani",
    "Babbu Maan",
    "Mika Singh",
    "S. P. B. Charan",
    "Shankar Mahadevan",
    "Sukhjinder virk",
    "Pawan Singh",
    "Shabab Sabri",
    "KK",
    "Aditya Narayan",
    "Daler Mehndi",
    "Navin Prabhakar",
    "Unnikrishnan",
    "Babul Supriyo",
    "Neeraj Shridhar",
    "Joseph Vijay",
    "Biju Narayanan",
    "Parthiv Gohil",
    "Pradip Somasundaran",
    "Sonu Nigam",
    "A. R. Rahman",
    "Roop Kumar Rathod",
    "Zubeen Garg",
    "Rajesh Krishnan",
    "Sukhwinder Singh",
    "M. M. Keeravani",
    "Master Saleem",
    "Shaan",
    "Kumar Sanu",
    "Sudesh Bhosle",
    "Mano",
    "G. Venugopal",
    "Vinod Rathod",
    "Mohammed Aziz",
    "M. G. Sreekumar",
    "Gurdas Maan",
    "Kamal Haasan",
    "Abhijeet Bhattacharya",
    "Unni Menon",
    "Puneeth Rajkumar",
    "Pankaj Udhas",
    "Shabbir Kumar",
    "Udit Narayan",
    "Anwar",
    "Suresh Wadkar",
    "Hariharan",
    "Lucky Ali",
    "Remo Fernandes",
    "Shailender Singh",
    "Nadeem Saifi",
    "Bappi Lahiri",
    "Nitin Mukesh",
    "S. P. Balasubrahmanyam",
    "Amit Kumar",
    "Jagjit Singh",
    "Dr. Rajkumar",
    "R. D. Burman",
    "P. Jayachandran",
    "Bhupinder Singh",
    "Jayanta Hazarika",
    "K. J. Yesudas",
    "Malaysia Vasudevan",
    "Mahendra Kapoor",
    "Manabendra Mukhopadhyay",
    "Kozhikode Abdul Kader",
    "P. B. Sreenivas",
    "Shyamal Mitra",
    "T. M. Soundararajan",
    "Kishore Kumar",
    "Talat Mahmood",
    "Dwijen Mukhopadhyay",
    "Mohammed Rafi",
    "Manna Dey",
    "Bhupen Hazarika",
    "Ghantasala",
    "Bhimsen Joshi",
    "Mukesh",
    "Dhananjay Bhattacharya",
    "Hemanta Mukherjee",
    "G. M. Durrani",
    "S. D. Burman",
    "K. L. Saigal",
    "Pankaj Mullick",
    "Gursimran Singh Sidhu"
];

let total_playlists = 0;

async function fetchPlaylists(token,offset = 0) {
    const response = await axios.get(`https://api.spotify.com/v1/browse/categories/0JQ5DAqbMKFHCxg5H5PtqW/playlists?offset=${offset}&limit=20`, {
        headers: { 'Authorization':  token },
    });

    const data = response.data;

    data['playlists']['items'].forEach(item => {
        ID_list.push(item['id']);
    });

    total_playlists = data['playlists']['total'];

    if (ID_list.length < total_playlists) {
        return fetchPlaylists(token,offset + 20);
    }else{
        return token;
    
    }
}

async function fetchTitle(token,offset=0){
    for (const ID of ID_list) {
        const response = await axios.get(`https://api.spotify.com/v1/playlists/${ID}/tracks?offset=${offset}&limit=100`, {
            headers: { 'Authorization':  token },
        });

        const data = response.data;

        data['items'].forEach(item => {
            if(item['track']['album']['artists'][0]['name'] && !Title_list.includes(item['track']['album']['artists'][0]['name'])){
                Title_list.push(item['track']['album']['artists'][0]['name']);
                console.log(item['track']['album']['artists'][0]['name']);
            }
        });
    }
}

const authOptions = {
    method: 'post',
    url: 'https://accounts.spotify.com/api/token',
    headers: {
        'Authorization': 'Basic ' + (Buffer.from(process.env.client_id + ':' + process.env.client_secret).toString('base64')),
        'Content-Type': 'application/x-www-form-urlencoded'
    },
    data: qs.stringify({
        grant_type: 'client_credentials'
    })
};

axios(authOptions)
    .then(response => {
        if (response.status === 200) {
            const token = response.data.token_type + ' ' + response.data.access_token;
            console.log(token);
            return token;
        }
    })
    .then(token => fetchPlaylists(token))
    .then(token => fetchTitle(token))
    .then(()=>{
        console.log(Title_list.length);
        // copy(Title_list);
    })
    .catch(error => {
        console.error(`Error getting access token: ${error}`);
    });

module.exports = Title_list;